# Generated by Django 5.1 on 2026-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='carte_vitale_number',
            field=models.CharField(blank=True, help_text='Numero de securite sociale (15 chiffres) - donnee sensible, usage encadre.', max_length=15),
        ),
    ]
