# Generated by Django 5.1 on 2026-09-05 18:16

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_carte_vitale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='carte_vitale_number',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Numero de securite sociale (15 chiffres) - donnee sensible, chiffree en base.', max_length=15),
        ),
    ]
