# Generated by Django 5.1 on 2026-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='consultation_price_cents',
            field=models.PositiveIntegerField(default=0, help_text="Tarif de consultation en centimes (0 = non renseigné). Utilisé pour pré-remplir les notes d'honoraires."),
        ),
    ]
