# Generated by Django 5.1 on 2026-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_practitioner_consultation_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='is_listed',
            field=models.BooleanField(default=True, help_text="Visible dans l'annuaire public de recherche."),
        ),
    ]
