# Generated by Django 5.1 on 2026-09-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_practitioner_address_practitioner_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_account',
            field=models.ForeignKey(blank=True, help_text='Pour un compte secrétaire : le titulaire pour le compte duquel il agit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Titulaire'), ('secretary', 'Secrétaire')], default='owner', max_length=20),
        ),
    ]
