# Generated by Django 5.1 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_owner_account_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='deposit_amount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Acompte en centimes exigé à la réservation en ligne (0 = aucun acompte requis).'),
        ),
    ]
