# Generated by Django 5.1 on 2026-09-09 16:19

import apps.accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_practitioner_deposit_amount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Secret TOTP (authentification à deux facteurs), chiffré en base.', max_length=32),
        ),
    ]
