# Generated by Django 5.1 on 2026-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_otp_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='offers_teleconsultation',
            field=models.BooleanField(default=False, help_text='Si activé, un lien de visioconférence (Jitsi Meet) est proposé sur chaque rendez-vous.'),
        ),
    ]
