# Generated by Django 5.1 on 2026-09-10 08:37

import apps.accounts.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('access_token', apps.accounts.fields.EncryptedCharField(max_length=512)),
                ('refresh_token', apps.accounts.fields.EncryptedCharField(max_length=512)),
                ('token_expiry', models.DateTimeField()),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('sync_busy_from_google', models.BooleanField(default=True, help_text="Bloquer les créneaux CabinBook qui chevauchent un événement de l'agenda Google perso.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to='accounts.practitioner')),
            ],
            options={
                'verbose_name': 'Connexion Google Calendar',
            },
        ),
    ]
