# Generated by Django 5.1 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_googlecalendarconnection'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['is_listed', 'is_active'], name='practitioner_listed_active_idx'),
        ),
    ]
