# Generated by Django 5.1 on 2026-09-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_sessionnote_waitlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée')], default='unpaid', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.appointment')),
            ],
            options={
                'verbose_name': "Note d'honoraires",
                'verbose_name_plural': "Notes d'honoraires",
                'ordering': ['-created_at'],
            },
        ),
    ]
