# Generated by Django 5.1 on 2026-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée'), ('refunded', 'Remboursée')], default='unpaid', max_length=20),
        ),
    ]
