# Generated by Django 5.1 on 2026-09-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_is_active'),
        ('appointments', '0002_availabilityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='series_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Toutes les semaines'), ('biweekly', 'Toutes les deux semaines'), ('monthly', 'Tous les mois')], max_length=20)),
                ('first_start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('occurrences_total', models.PositiveIntegerField(blank=True, null=True)),
                ('until', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to='accounts.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to='accounts.practitioner')),
            ],
            options={
                'verbose_name': 'Série de rendez-vous',
                'verbose_name_plural': 'Séries de rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmentseries'),
        ),
    ]
