# Generated by Django 5.1 on 2026-09-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_practitioner_consultation_price_cents'),
        ('appointments', '0003_appointment_series_position_appointmentseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_note', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Note de séance',
                'verbose_name_plural': 'Notes de séance',
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Ex: disponible le matin uniquement', max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('notified', 'Prévenu'), ('booked', 'Réservé'), ('cancelled', 'Annulé')], default='waiting', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='accounts.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='accounts.practitioner')),
            ],
            options={
                'verbose_name': "Entrée liste d'attente",
                'verbose_name_plural': "Liste d'attente",
                'ordering': ['created_at'],
            },
        ),
    ]
