# Generated by Django 5.1 on 2026-09-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_practitioner_address_practitioner_city_and_more'),
        ('appointments', '0004_sessionnote_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Masqué par le praticien (contenu inapproprié).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.practitioner')),
            ],
            options={
                'verbose_name': 'Avis patient',
                'verbose_name_plural': 'Avis patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
