# Generated by Django 5.1 on 2026-09-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_room'),
        ('appointments', '0005_appointment_reminder_whatsapp_sent_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Salle du cabinet occupée par ce RDV (optionnel, plan Cabinet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.room'),
        ),
    ]
