# Generated by Django 5.1 on 2026-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, help_text="ID de l'événement correspondant dans le Google Calendar du praticien, si connecté.", max_length=255),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='blocked_by_external_calendar',
            field=models.BooleanField(default=False, help_text="Bloqué automatiquement car il chevauche un événement de l'agenda Google perso du praticien (pas un vrai RDV)."),
        ),
    ]
