# Generated by Django 5.1 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_practitioner_practitioner_listed_active_idx'),
        ('appointments', '0007_appointment_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner', 'start_time'], name='appt_practitioner_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner', 'status', 'start_time'], name='appt_practitioner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['practitioner', 'is_available', 'start_time'], name='slot_practitioner_avail_idx'),
        ),
    ]
